import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;

import javax.swing.BoxLayout;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.OverlayLayout;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Daar375
 */
public class UI extends javax.swing.JFrame {
    
    	private Control control;


    /**
     * Creates new form UI
     */
    public UI(Control pcontrol) {
    	control=pcontrol;
        initComponents();
    }

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {  
    	jPanel1.removeAll();
    	jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.PAGE_AXIS));
		if(!Busqueda.getText().isEmpty()){
			
			control.Search(Busqueda.getText());
			while(control.getResult().get(0).getHTML()==null){}
			int numofSearch = control.getResult().size();
			int index = 0;
			while(numofSearch!=index){
		        JScrollPane jScroll = new javax.swing.JScrollPane();
				JEditorPane HTMLPanel = new JEditorPane();	
				JLabel time = new JLabel();
				HTMLPanel.setContentType("text/html");
				HTMLPanel.getDocument().putProperty("IgnoreCharsetDirective",Boolean.TRUE);	
				HTML tool = new HTML();
				HTMLPanel.setText(control.getResult().get(index).getHTML());
				HTMLPanel.setEditable(false);
				time.setText("Duracion: "+control.getResult().get(index).getTime());
				jScroll.setViewportView(HTMLPanel);
				jScroll.setSize(600, 300);
				jScroll.setVisible(true);
				time.setVisible(true);
				time.setSize(300, 300);
				jPanel1.add(time);

				jPanel1.add(jScroll);
				jPanel1.validate();
				jPanel1.repaint();
				
				index++;
			}
			

			
		}
    }                                       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Busqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Bbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Busqueda)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bbuscar)
                .addGap(789, 789, 789)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Bbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// <// </editor-fold>    
                                     

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton Bbuscar;
    private javax.swing.JTextField Busqueda;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
